import os
import sys
import requests
from dotenv import load_dotenv

# Add project root to path to allow imports from src
sys.path.append(os.getcwd())

# Import the upload function directly
# Note: This requires youtube_server.py dependencies to be installed
try:
    from src.mcp.youtube_server import youtube_upload_video
except ImportError as e:
    print(f"Error importing youtube_server: {e}")
    sys.exit(1)

load_dotenv()

LOCAL_FILE = "downloaded_video.mp4"

def download_video():
    print("Reading video URL...")
    try:
        with open("video_url.txt", "r") as f:
            url = f.read().strip()
    except FileNotFoundError:
        print("Error: video_url.txt not found.")
        return None

    print(f"Downloading video from {url[:50]}...")
    try:
        r = requests.get(url, stream=True)
        r.raise_for_status()
        with open(LOCAL_FILE, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)
        print("Download complete.")
        return True
    except Exception as e:
        print(f"Download failed: {e}")
        return False

def log(msg):
    print(msg)
    with open("upload_log.txt", "a", encoding="utf-8") as f:
        f.write(msg + "\n")

def upload():
    log("Uploading to YouTube...")
    try:
        if not os.path.exists(LOCAL_FILE):
             log(f"Error: File {LOCAL_FILE} does not exist.")
             return

        result = youtube_upload_video(
            file_path=LOCAL_FILE,
            title="FastKOL Auto-Gen Video (Manual Recover)",
            description="Video generated by HeyGen via FastKOL workflow (Manually Recovered).",
            privacy_status="unlisted"
        )
        log("\nUpload Success!")
        log(f"Video ID: {result.get('video_id')}")
        log(f"Video URL: {result.get('video_url')}")
    except Exception as e:
        log(f"\nUpload Failed: {e}")
        import traceback
        log(traceback.format_exc())

if __name__ == "__main__":
    # Clear log file
    with open("upload_log.txt", "w") as f: f.write("Starting upload process...\n")
    
    if download_video():
        upload()
